### ISSUE TITLE
Can't load prj.xml files.

### ISSUE THREAD

**Issue by IOBYTE** [vladracula/TorcsJTE#3]
I'm getting an exception when loading an existing project file with the bugfix/gui-refactor branch.
```
Java version    : 17.0.2
OS              : Windows 10
OS architecture : amd64
OS version      : 10.0
Exception in thread "AWT-EventQueue-0" java.lang.Error: Unresolved compilation problem: 
	The method setEntityResolver(EntityResolver) in the type SAXBuilder is not applicable for the arguments (NoOpEntityResolver)

	at plugin.torcs.XmlReader.readFromFile(XmlReader.java:347)
	at plugin.torcs.XmlReader.readXml(XmlReader.java:54)
	at plugin.torcs.TorcsPlugin.readFile(TorcsPlugin.java:90)
	at gui.EditorFrame.openProject(EditorFrame.java:217)
	at action.OpenAction.actionToPerformed(OpenAction.java:20)
	at action.AbstractEditorAction$InnerActionImpl.actionPerformed(AbstractEditorAction.java:46)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
I also have these errors:
```
EntityResolver cannot be resolved to a type	NoOpEntityResolver.java	/TorcsJTE/src/main/java/plugin/torcs	line 34	Java Problem
InputSource cannot be resolved to a type	NoOpEntityResolver.java	/TorcsJTE/src/main/java/plugin/torcs	line 36	Java Problem
InputSource cannot be resolved to a type	NoOpEntityResolver.java	/TorcsJTE/src/main/java/plugin/torcs	line 37	Java Problem
The method setEntityResolver(EntityResolver) in the type SAXBuilder is not applicable for the arguments (NoOpEntityResolver)	XmlReader.java	/TorcsJTE/src/main/java/plugin/torcs	line 347	Java Problem
The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml	NoOpEntityResolver.java	/TorcsJTE/src/main/java/plugin/torcs	line 23	Java Problem
The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml	NoOpEntityResolver.java	/TorcsJTE/src/main/java/plugin/torcs	line 24	Java Problem
```
I would like to modify this app to add Speed Dreams support but I want to start with a working version.  Is this branch the one I should start with?

I have already added support for changing the track version to 3, 4 or 5 in the Header section.  I want to add support for Pits section attributes "start buildings" and "end buildings" so I can generate tracks for testing the trackgen tool.

**Comment by vladracula** [comment]
Hi,
It is not tested with java 17 and windows at all. I tested it with jdk 11 and linux only. Anyway if you want to fork it use the master branch.
